create day:
  mkdir -p "{{day}}"
  cp prog_template.py "{{day}}/prog.py" -n
  touch "{{day}}/input.txt"
  touch "{{day}}/example.txt"
  echo "Created directory for {{day}}"
  just get-input {{day}}

session := `grep -oE 'session=[^;[:space:]]+' cookies.txt | head -n1 | cut -d= -f2`

get-input day:
  echo "Fetching input for {{day}}"
  echo "session: {{session}}"
  curl --output "{{day}}/input.txt" -b "session={{session}}" -v -L "https://adventofcode.com/2025/day/{{replace(day, 'day', '')}}/input" 
